pool:
  vmImage: 'ubuntu-latest'

trigger:
  - master

steps:
  # Step 1: Install dependencies
  - script: |
      npm install
    displayName: 'Install Dependencies'

  # Step 2: Run tests
  - script: |
      npm test
    displayName: 'Run Tests'

  # Step 3: Publish test results
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-results.xml'
    displayName: 'Publish Test Results'

  # Step 4: Archive source code
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)'
      includeRootFolder: false
    displayName: 'Archive Sources'

  # Step 5: Publish build artifacts
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
    displayName: 'Publish Artifact'

