pool:
  vmImage: 'ubuntu-latest'

trigger:
  - master

steps:
  # Step 1: Ensure Python 2 is installed
  - script: |
      sudo apt-get update
      sudo apt-get install -y python2
    displayName: 'Install Python 2'

  # Step 2: Install dependencies
  - script: |
      npm install
    displayName: 'Install Dependencies'

  # Step 3: Run tests
  - script: |
      npm test
    displayName: 'Run Tests'

  # Step 4: Publish test results
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-results.xml'
    displayName: 'Publish Test Results'

  # Step 5: Archive source code
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)'
      includeRootFolder: false
    displayName: 'Archive Sources'

  # Step 6: Publish build artifacts
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
    displayName: 'Publish Artifact'


